# Generated by Django 5.2.1 on 2025-05-22 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRDVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='BRDs/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BRD', 'BRD'), ('KM', 'KAAM'), ('HW', 'HELLOWORLD'), ('SG', 'SWIGGY'), ('OLA', 'OLA'), ('UB', 'UBER'), ('ZM', 'ZOMATO')], max_length=10)),
            ],
        ),
    ]
