# Generated by Django 5.2.1 on 2025-05-29 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brd', '0002_alter_brdvarity_options_brdvarity_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brdvarity',
            options={},
        ),
        migrations.CreateModel(
            name='brdcertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('BRD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='brd.brdvarity')),
            ],
        ),
        migrations.CreateModel(
            name='BRDReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('BRD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='brd.brdvarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
